### PR TITLE
Project: Building with Bootstrap for Responsive Design

### PR DESCRIPTION
**Pull request by edxco**

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

 WOW, what project! ⭐


#### Hey @edxco Is a pleasure to review such a good project! Congrats for the amazing work you already did, the project looks awesome! It breaks my heart 💔 not approve it right away, but I swear, we're almost done, there are just some minor changes that you have to implement to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [ ] Remove that big gap (large screens)
image
- [ ] In medium screens you have a horizontal bar, which means that something is overflowing. Tip: use `* { border: 1px solid red }` to spot the element that is causing that.
image

[OPTIONAL CHANGES] 
- [ ] I don't have optional changes, since your project looks awesome.

## Summary (AWESOMENESS ⭐)
✨ Team, I know a great project when I see one. And wow! Thats one of the best newsweek projects I've ever reviewed!
✨ Nice usage of bootstrap!
✨ Your page looks AWESOME! 👏
✨ Awesome CSS practices, congrats 😎
✨ Don't have over repeated css rules, wow, that's a great point to note! 👏
✨ Again, good job with that project, it looks almost perfect💥
✨ Very organized repo 🗃
✨ Perfect usage of semantic HTML with `<article>` ,` <section>` tags 🥇
✨ You got my attention, I'll keep my eyes on you! Keep up the good work! 🐱‍👓

## Please make the required changes and resubmit for a new code review once you are ready💪
That was close

## As always, I wish you all the very best and see you at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by edxco** [comment]
- Remove gap between images and text
- Fix overflowing elements on medium size

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
# Great job guys you have made an amazing job, you still need to work on your readme file.

- [ ] the screenshots in the readme are not related to this project please fix them.

### Other than that you are all good, fix this issue and ask for another code review.
## Happy Coding :tophat:

**Comment by edxco** [comment]
- Readme update

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Hi, it's me again thank you for making the required changes :clap: 

now you can merge to master your project is approved

## Happy Coding :tophat:

**Pull request merged**
